# Generated by Django 3.2.12 on 2022-05-25 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_accounts',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('unique_image', models.CharField(max_length=250)),
                ('user_pass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='lion', max_length=200)),
                ('fails', models.PositiveSmallIntegerField(default=0)),
                ('login_link', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('reset_link', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
