# Generated by Django 3.2.12 on 2022-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_accounts',
        ),
    ]
