# Generated by Django 3.2.12 on 2022-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_logininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='image_name',
            field=models.CharField(default='lion', max_length=200),
        ),
    ]
